export const sample_vinyls: any[] = [
  {
    id: '1',
    artist: 'Pearl Jam',
    albumTitle: 'Vs.: 30th Anniversary (2LP)',
    genre: 'Grunge',
    year: 1992,
    format: 'LP',
    price: 41.9,
    favorite: true,
    imageUrl: 'assets/vinyl-1.jpg',
  },

  {
    id: '2',
    artist: 'Air',
    albumTitle: 'Moon Safari',
    genre: 'Electronica',
    year: 1998,
    format: 'LP',
    price: 21.9,
    favorite: false,
    imageUrl: 'assets/vinyl-2.jpg',
  },

  {
    id: '3',
    artist: 'Alice In Chains',
    albumTitle: 'Facelift: 30th Anniversary',
    genre: 'Grunge',
    year: 2020,
    format: 'LP',
    price: 27.9,
    favorite: true,
    imageUrl: 'assets/vinyl-3.jpg',
  },

  {
    id: '4',
    artist: 'Allah-Las',
    albumTitle: 'Allah-Las',
    genre: 'Garage Rock',
    year: 2012,
    format: 'LP',
    price: 28.9,
    favorite: true,
    imageUrl: 'assets/vinyl-4.jpg',
  },

  {
    id: '5',
    artist: 'Archive',
    albumTitle: ' Take My Head',
    genre: 'Trip hop',
    year: 1999,
    format: 'LP',
    price: 31.9,
    favorite: true,
    imageUrl: 'assets/vinyl-5.jpg',
  },

  {
    id: '6',
    artist: 'Audioslave',
    albumTitle: 'Audioslave',
    genre: 'Hard rock',
    year: 2002,
    format: 'LP',
    price: 27.9,
    favorite: false,
    imageUrl: 'assets/vinyl-6.jpg',
  },

  {
    id: '7',
    artist: 'Bad Religion',
    albumTitle: 'The Gray Race',
    genre: 'Punk rock',
    year: 1996,
    format: 'LP',
    price: 25.9,
    favorite: false,
    imageUrl: 'assets/vinyl-7.jpg',
  },

  {
    id: '8',
    artist: 'Baroness',
    albumTitle: 'Blue Record (Picture Disc 2LP)',
    genre: 'Sludge metal',
    year: 2009,
    format: 'LP',
    price: 33.9,
    favorite: true,
    imageUrl: 'assets/vinyl-8.jpg',
  },

  {
    id: '9',
    artist: 'Kyuss',
    albumTitle: 'Welcome to Sky Valley',
    genre: 'Stoner Rock',
    year: 1994,
    format: 'LP',
    price: 9.9,
    favorite: true,
    imageUrl: 'assets/vinyl-9.jpg',
  },
  {
    id: '10',
    artist: 'Polaris',
    albumTitle: 'Fatalism',
    genre: 'Metalcore',
    year: 2023,
    format: 'LP',
    price: 30,
    favorite: true,
    imageUrl: 'assets/vinyl-10.jpg',
  },
  {
    id: '11',
    artist: 'Of Mice & Men',
    albumTitle: 'Tether',
    genre: 'Metalcore',
    year: 2023,
    format: 'LP',
    price: 30,
    favorite: true,
    imageUrl: 'assets/vinyl-11.jpg',
  },
  {
    id: '12',
    artist: 'Tool',
    albumTitle: 'Lateralus',
    genre: 'Progressive Metal',
    year: 2005,
    format: '2LP',
    price: 150,
    favorite: true,
    imageUrl: 'assets/vinyl-12.jpg',
  },
  {
    id: '13',
    artist: 'Fugazi',
    albumTitle: 'Repeater',
    genre: 'Post-Hardcore',
    year: 1990,
    format: 'LP',
    price: 25,
    favorite: true,
    imageUrl: 'assets/vinyl-13.jpg',
  },

  {
    id: '14',
    artist: 'Spiritbox',
    albumTitle: 'Eternal Blue',
    genre: 'Metalcore',
    year: 2021,
    format: 'LP',
    price: 25,
    favorite: true,
    imageUrl: 'assets/vinyl-14.jpg',
  },
  {
    id: '15',
    artist: 'Sleep Token',
    albumTitle: 'Take Me Back To Eden',
    genre: 'Progressive Metal',
    year: 2023,
    format: '2LP',
    price: 40,
    favorite: true,
    imageUrl: 'assets/vinyl-15.jpg',
  },
  {
    id: '16',
    artist: 'Bring Me The Horizon',
    albumTitle: 'Post Human: Survival Horror',
    genre: 'Metalcore',
    year: 2020,
    format: 'LP',
    price: 30,
    favorite: true,
    imageUrl: 'assets/vinyl-16.jpg',
  },
  {
    id: '17',
    artist: 'Nine Inch Nails',
    albumTitle: 'The Downward Spiral',
    genre: 'Industrial Metal',
    year: 1994,
    format: '2LP',
    price: 50,
    favorite: true,
    imageUrl: 'assets/vinyl-17.jpg',
  },

  {
    id: '18',
    artist: 'Isis',
    albumTitle: 'Oceanic',
    genre: 'Post-Metal',
    year: 2002,
    format: '2LP',
    price: 60,
    favorite: true,
    imageUrl: 'assets/vinyl-18.jpg',
  },
  {
    id: '19',
    artist: 'Massive Attack',
    albumTitle: 'Mezzanine',
    genre: 'Trip Hop',
    year: 1998,
    format: '2LP',
    price: 60,
    favorite: true,
    imageUrl: 'assets/vinyl-19.jpg',
  },
  {
    id: '20',
    artist: 'Architexts',
    albumTitle: 'Lost Forever // Lost Together',
    genre: 'Metalcore',
    year: 2014,
    format: 'LP',
    price: 17,
    favorite: true,
    imageUrl: 'assets/vinyl-20.jpg',
  },
];

export const sample_users: any[] = [
  {
    name: 'Jane Austin',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Rome',
    isAdmin: true,
  },

  {
    name: 'John Green',
    email: 'john@gmail.com',
    password: '123456',
    address: 'Milan',
    isAdmin: false,
  },

  {
    name: 'Kate Black',
    email: 'kate@gmail.com',
    password: '12345645646',
    address: 'Atlanda',
    isAdmin: true,
  },

  {
    name: 'Nick Sane',
    email: 'nick@gmail.com',
    password: '123456789',
    address: 'Athens',
    isAdmin: false,
  },

  {
    name: 'Jake White',
    email: 'jake@gmail.com',
    password: '123455555',
    address: 'Paris',
    isAdmin: true,
  },

  {
    name: 'Josh Bale',
    email: 'josh@gmail.com',
    password: '1234567890',
    address: 'New York',
    isAdmin: true,
  },

  {
    name: 'Mary Jane',
    email: 'mary@gmail.com',
    password: '1234578',
    address: 'Lisbon',
    isAdmin: false,
  },

  {
    name: 'Joanne Dean',
    email: 'joanne@gmail.com',
    password: '12345785',
    address: 'Barcelona',
    isAdmin: true,
  },

  {
    name: 'Mark Guy',
    email: 'mark@gmail.com',
    password: '123454443',
    address: 'Lyon',
    isAdmin: true,
  },

  {
    name: 'June Phillips',
    email: 'june@gmail.com',
    password: '0012345',
    address: 'Oslo',
    isAdmin: false,
  },

  {
    name: 'Peter Lucky',
    email: 'peter@gmail.com',
    password: '11212345',
    address: 'Chicago',
    isAdmin: true,
  },
];
